<?php

$title = "Nasz cel";

$contentLOG = $content = $contentAdmin = "
                        <h2>Czy opinie w internecie są prawdziwe?</h2>         
                        
                        <div id='slideshow'>
                            <img src='images/home1.jpg' alt='photo1' class='active'>
                            <img src='images/home2.jpg' alt='photo2' >
                            <img src='images/home3.jpg' alt='photo3' >
                        </div>
                        
                        <br>
                        <p style='text-align:justify'>Zastanawiałeś/aś się kiedyś czy opinie, z którymi masz styczność podczas codziennego surfowania po internecie są prawdziwe? Na to pytanie nie ma jednoznacznej odpowiedzi. </p>
                        <p style='text-align:justify'>Zastanów się ile razy dokonałeś/aś zakupu przez internet kierując się opiniami innych użytkowników. Raz? Dwa? A może robisz to nieustannie? Ze statystyk wynika, że około <span style='color:green;'>22%</span> ludzi w Polsce wykonuje regularne zakupy przez internet, a aż <span style='color:green;'>68%</span> polaków dokonało przynajmniej jednego zakupu przez internet. Jest to spowodowane coraz to lepszymi serwisami, które umożliwiają wirtualny handel. W mgnieniu oka powstają liczne strony internetowe kolejnych i kolejnych sklepów stacjonarnych. Dlaczego więc nie robić zakupów przez internet?</p>
                        <p style='text-align:justify'>Zakupy przez internet są niewątpliwie lepszym wyborem. Składa się na to wiele czynników, ja wymienię kilka z nich. Po pierwsze - taniej. Tak! Taniej! Dlaczego? Idąc do sklepu stacjonarnego mamy do wyboru jedną cenę danego produktu i na tym się kończy nasze pole do popisu. W internecie możemy znaleźć ten produkt na wielu aukcjach, często w niższej, a nawet promocyjnej cenie. Ktoś zaraz powie - \"Halo, pan się pomylił. Przecież trzeba zapłacić za przesyłkę\". Moja odpowiedź brzmi - tak, trzeba zapłacić za przesyłkę. Ale koszt przesyłek waha się między 5 zł, a 15 zł. Ale i tak wychodzi taniej przez internet, koszt produktu + koszt przesyłki. Dlaczego? Jak już wcześniej wspomniałem, nie każdy sklep oferuje tą samą cenę za ten sam produkt. Np. w Warszawie może być promocja 50% na jakieś jeansy, kiedy w Lublinie nie będzie żadnej promocji.</p>
                        <p style='text-align:justify'>Mam nadzieję, że zrozumiałeś/aś moje wypociny i przebrnąłeś/aś przez ten długi akapit. Czas przejść do opinii.</p>
                        <p style='text-align:justify'>Tutaj pojawia się problem. Bo o ile połowa opinii w internecie jest prawdziwa, o tyle druga część to opinie ale kogo? Nie, nie św. Mikołaja ;) Są to opinie właścicieli sklepów. Manipulują oni swoimi klientami dodając opinie na swoich stronach/aukcjach. Ma to na celu jak już się zapewne domyślacie, zwiększenie sprzedaży swoich produktów. Metody działania takich \"oszustów\" są różne. Jeżeli ma dostęp do strony - jest jej adminem to nic nie stoi na przeszkodzie, <img style='padding-left:10px;padding-top:10px' class='allegImage' src='images/allegReview.jpg' alt='photo1' width='300px' height='150px' align='right'> aby dodać taką opinię. Trudniejsza sytuacja jest w przypadku allegro. Tam opinie są ściśle strzeżone, ale i na to sprzedawcy znaleźli rozwiązanie. Jakie? Bardzo proste. Wykupują opinie! Tak! Dobrze widzisz, wykupują je. Ale chwila, zaraz pomyślisz, że to się nie opłaca. A pomyśl, sprzedawca płaci 10 ludziom na dodanie 10 pozytywnych opinii. Koszt pojedynczej opinii to 50 zł. Sprzedawca traci 500 zł. Ale jak je odzyskuje? A jak myślisz, po ilu dniach zwróci mu się to 500 zł? 10 pozytywnych opinii. Ludzie będą chętnie kupować produkt czy też nie? Odpowiedź jest jasna, kupią! Nie ma w tej metodzie nic nielegalnego, ale prowadzi to do błędnego postrzegania wielu produktów na rynku. I tu z pomocą przychodzi strona Opinius!</p>
                        <p style='text-align:justify'>Czym ta strona różni się od pozostałych? Tym, że nasze opinie są wiarygodne. Sklepy nie płacą nam za reklamę. Nie dodajemy swoich \"sztucznych\" opinii. Można z pewnością poznać to po ilości negatywnych głosów. Tak! Nie usuwamy opinii. Zależy nam na <span style='color:green;'>wiarygodności</span>. Recenzje zebrane na tej stronie pomogą ci dokonać rzetelnego wyboru. Zatem nie pozostaje Ci nic innego, jak zacząć szukać swojego wymarzonego produktu i sprawdzić opinie na jego temat!</p>
                        <p style='text-align:justify'>Nie zapomnij dodać własnej opinii ;)</p>";
